# Generated by Django 5.0.3 on 2024-03-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rent_date',
        ),
        migrations.AlterField(
            model_name='rent',
            name='rented',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
