# Generated by Django 5.0.3 on 2024-03-31 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_rent_rent_date_alter_rent_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rented',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
