# Generated by Django 5.0.3 on 2024-04-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_resturant_store_remove_rent_game_remove_rent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
    ]
